<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AnimeCatalogSeeder extends Seeder
{
    public function run()
    {
        $genreTable      = $this->db->table('genres');
        $animeTable      = $this->db->table('animes');
        $animeGenreTable = $this->db->table('anime_genres');

        $animeGenreTable->delete();
        $animeTable->delete();
        $genreTable->delete();

        $now = date('Y-m-d H:i:s');

        $genres = [
            ['name' => 'Action', 'slug' => 'action', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Adventure', 'slug' => 'adventure', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Fantasy', 'slug' => 'fantasy', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Drama', 'slug' => 'drama', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Romance', 'slug' => 'romance', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Comedy', 'slug' => 'comedy', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sci-Fi', 'slug' => 'sci-fi', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mystery', 'slug' => 'mystery', 'created_at' => $now, 'updated_at' => $now],
        ];

        $genreTable->insertBatch($genres);

        $genreIds = [];
        foreach ($genreTable->get()->getResultArray() as $genre) {
            $genreIds[$genre['slug']] = (int) $genre['id'];
        }

        $animes = [
            [
                'title' => 'Sen to Chihiro no Kamikakushi',
                'slug' => 'sen-to-chihiro-no-kamikakushi',
                'original_title' => '千と千尋の神隠し',
                'synopsis' => 'Chihiro egy különös szellemvilágba kerül, ahol saját bátorságával és kitartásával kell megmentenie a családját.',
                'poster_image' => '/img/popular/popular-1.jpg',
                'type' => 'Movie',
                'status' => 'Finished',
                'studio' => 'Studio Ghibli',
                'aired_from' => '2001-07-20',
                'aired_to' => '2001-07-20',
                'duration' => '125 min',
                'quality' => 'HD',
                'episode_current' => 1,
                'episode_total' => 1,
                'views_count' => 9141,
                'comments_count' => 11,
                'score' => 8.90,
                'score_count' => 1515,
                'rating_avg' => 8.8,
                'rating_count' => 161,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['adventure', 'fantasy', 'drama'],
            ],
            [
                'title' => 'Kizumonogatari III: Reiketsu-hen',
                'slug' => 'kizumonogatari-iii-reiketsu-hen',
                'original_title' => '傷物語〈Ⅲ冷血篇〉',
                'synopsis' => 'Araragi végső összecsapásra készül, miközben döntést kell hoznia az emberi és természetfeletti oldala között.',
                'poster_image' => '/img/popular/popular-2.jpg',
                'type' => 'Movie',
                'status' => 'Finished',
                'studio' => 'Shaft',
                'aired_from' => '2017-01-06',
                'aired_to' => '2017-01-06',
                'duration' => '83 min',
                'quality' => 'HD',
                'episode_current' => 1,
                'episode_total' => 1,
                'views_count' => 8120,
                'comments_count' => 8,
                'score' => 8.77,
                'score_count' => 1204,
                'rating_avg' => 8.6,
                'rating_count' => 138,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['action', 'mystery', 'fantasy'],
            ],
            [
                'title' => 'Shirogane Tamashii-hen Kouhan-sen',
                'slug' => 'shirogane-tamashii-hen-kouhan-sen',
                'original_title' => '銀魂. 銀ノ魂篇 後半戦',
                'synopsis' => 'A Gintama fináléja egyszerre akciódús, komikus és érzelmes lezárást ad a hosszú kalandnak.',
                'poster_image' => '/img/popular/popular-3.jpg',
                'type' => 'TV',
                'status' => 'Finished',
                'studio' => 'Bandai Namco Pictures',
                'aired_from' => '2018-07-09',
                'aired_to' => '2018-10-08',
                'duration' => '24 min/ep',
                'quality' => 'HD',
                'episode_current' => 14,
                'episode_total' => 14,
                'views_count' => 10321,
                'comments_count' => 15,
                'score' => 8.75,
                'score_count' => 1410,
                'rating_avg' => 8.7,
                'rating_count' => 201,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['action', 'comedy', 'drama'],
            ],
            [
                'title' => 'Rurouni Kenshin: Meiji Kenkaku Romantan',
                'slug' => 'rurouni-kenshin-meiji-kenkaku-romantan',
                'original_title' => 'るろうに剣心 -明治剣客浪漫譚-',
                'synopsis' => 'A legendás kardforgató múltja elől menekülve próbál békés életet élni, de újra és újra harcba kényszerül.',
                'poster_image' => '/img/popular/popular-4.jpg',
                'type' => 'TV',
                'status' => 'Finished',
                'studio' => 'Gallop',
                'aired_from' => '1996-01-10',
                'aired_to' => '1998-09-08',
                'duration' => '24 min/ep',
                'quality' => 'HD',
                'episode_current' => 95,
                'episode_total' => 95,
                'views_count' => 7430,
                'comments_count' => 7,
                'score' => 8.31,
                'score_count' => 963,
                'rating_avg' => 8.1,
                'rating_count' => 112,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['action', 'adventure', 'drama'],
            ],
            [
                'title' => 'Mushishi Zoku Shou 2nd Season',
                'slug' => 'mushishi-zoku-shou-2nd-season',
                'original_title' => '蟲師 続章 後半エピソード',
                'synopsis' => 'Ginko tovább járja a vidéket, és misztikus mushi jelenségekkel kapcsolatos emberi sorsokat tár fel.',
                'poster_image' => '/img/popular/popular-5.jpg',
                'type' => 'TV',
                'status' => 'Finished',
                'studio' => 'Artland',
                'aired_from' => '2014-10-19',
                'aired_to' => '2014-12-21',
                'duration' => '24 min/ep',
                'quality' => 'HD',
                'episode_current' => 10,
                'episode_total' => 10,
                'views_count' => 6980,
                'comments_count' => 4,
                'score' => 8.68,
                'score_count' => 840,
                'rating_avg' => 8.9,
                'rating_count' => 96,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['drama', 'fantasy', 'mystery'],
            ],
            [
                'title' => 'Monogatari Series: Second Season',
                'slug' => 'monogatari-series-second-season',
                'original_title' => '〈物語〉シリーズ セカンドシーズン',
                'synopsis' => 'A különös lányok és démoni jelenések történetei tovább bonyolódnak Araragi körül.',
                'poster_image' => '/img/popular/popular-6.jpg',
                'type' => 'TV',
                'status' => 'Finished',
                'studio' => 'Shaft',
                'aired_from' => '2013-07-07',
                'aired_to' => '2013-12-29',
                'duration' => '25 min/ep',
                'quality' => 'HD',
                'episode_current' => 26,
                'episode_total' => 26,
                'views_count' => 8802,
                'comments_count' => 13,
                'score' => 8.76,
                'score_count' => 1330,
                'rating_avg' => 8.7,
                'rating_count' => 184,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['mystery', 'romance', 'comedy'],
            ],
            [
                'title' => 'Great Teacher Onizuka',
                'slug' => 'great-teacher-onizuka',
                'original_title' => 'グレート・ティーチャー・オニヅカ',
                'synopsis' => 'Egykori motoros bandatagból lesz tanár, aki meghökkentő, de működő módszerekkel segíti a diákjait.',
                'poster_image' => '/img/recent/recent-1.jpg',
                'type' => 'TV',
                'status' => 'Finished',
                'studio' => 'Pierrot',
                'aired_from' => '1999-06-30',
                'aired_to' => '2000-09-24',
                'duration' => '24 min/ep',
                'quality' => 'HD',
                'episode_current' => 43,
                'episode_total' => 43,
                'views_count' => 9541,
                'comments_count' => 21,
                'score' => 8.69,
                'score_count' => 1466,
                'rating_avg' => 8.8,
                'rating_count' => 205,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['comedy', 'drama'],
            ],
            [
                'title' => 'Fate/Zero 2nd Season',
                'slug' => 'fate-zero-2nd-season',
                'original_title' => 'Fate/Zero 2nd Season',
                'synopsis' => 'A Szent Grál-háború döntő szakasza könyörtelen csatákon és súlyos áldozatokon át vezet.',
                'poster_image' => '/img/recent/recent-4.jpg',
                'type' => 'TV',
                'status' => 'Finished',
                'studio' => 'ufotable',
                'aired_from' => '2012-04-08',
                'aired_to' => '2012-06-24',
                'duration' => '24 min/ep',
                'quality' => 'HD',
                'episode_current' => 12,
                'episode_total' => 12,
                'views_count' => 12041,
                'comments_count' => 18,
                'score' => 8.55,
                'score_count' => 1710,
                'rating_avg' => 8.4,
                'rating_count' => 233,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['action', 'fantasy', 'drama'],
            ],
            [
                'title' => 'The Seven Deadly Sins: Wrath of the Gods',
                'slug' => 'the-seven-deadly-sins-wrath-of-the-gods',
                'original_title' => '七つの大罪 神々の逆鱗',
                'synopsis' => 'Meliodas és társai újra harcba indulnak Britannia sorsáért, miközben sötét titkok kerülnek felszínre.',
                'poster_image' => '/img/recent/recent-6.jpg',
                'type' => 'TV',
                'status' => 'Finished',
                'studio' => 'Studio Deen',
                'aired_from' => '2019-10-09',
                'aired_to' => '2020-03-25',
                'duration' => '24 min/ep',
                'quality' => 'HD',
                'episode_current' => 24,
                'episode_total' => 24,
                'views_count' => 11020,
                'comments_count' => 16,
                'score' => 7.10,
                'score_count' => 1210,
                'rating_avg' => 7.3,
                'rating_count' => 164,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['action', 'adventure', 'fantasy'],
            ],
            [
                'title' => 'Boruto: Naruto Next Generations',
                'slug' => 'boruto-naruto-next-generations',
                'original_title' => 'BORUTO-ボルト- NARUTO NEXT GENERATIONS',
                'synopsis' => 'Naruto fia a saját útját keresi, miközben új veszélyek jelennek meg a shinobi világban.',
                'poster_image' => '/img/sidebar/tv-1.jpg',
                'type' => 'TV',
                'status' => 'Airing',
                'studio' => 'Pierrot',
                'aired_from' => '2017-04-05',
                'aired_to' => null,
                'duration' => '24 min/ep',
                'quality' => 'HD',
                'episode_current' => 293,
                'episode_total' => null,
                'views_count' => 131541,
                'comments_count' => 44,
                'score' => 6.85,
                'score_count' => 4515,
                'rating_avg' => 7.0,
                'rating_count' => 482,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['action', 'adventure', 'fantasy'],
            ],
            [
                'title' => 'Sword Art Online Alicization: War of Underworld',
                'slug' => 'sword-art-online-alicization-war-of-underworld',
                'original_title' => 'ソードアート・オンライン アリシゼーション War of Underworld',
                'synopsis' => 'Az Underworld végső csatája elkezdődik, miközben Asuna és Kirito szövetségesei újra hadba állnak.',
                'poster_image' => '/img/sidebar/tv-3.jpg',
                'type' => 'TV',
                'status' => 'Finished',
                'studio' => 'A-1 Pictures',
                'aired_from' => '2019-10-13',
                'aired_to' => '2019-12-29',
                'duration' => '24 min/ep',
                'quality' => 'HD',
                'episode_current' => 12,
                'episode_total' => 12,
                'views_count' => 19410,
                'comments_count' => 26,
                'score' => 7.60,
                'score_count' => 2210,
                'rating_avg' => 7.8,
                'rating_count' => 276,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['action', 'adventure', 'fantasy', 'romance'],
            ],
            [
                'title' => 'Fate/stay night: Heaven\'s Feel I. Presage Flower',
                'slug' => 'fate-stay-night-heavens-feel-i-presage-flower',
                'original_title' => '劇場版「Fate/stay night [Heaven\'s Feel] I. presage flower」',
                'synopsis' => 'Shirou története sötétebb és személyesebb irányt vesz, amikor a Grál-háború más arcát is megismeri.',
                'poster_image' => '/img/sidebar/tv-4.jpg',
                'type' => 'Movie',
                'status' => 'Finished',
                'studio' => 'ufotable',
                'aired_from' => '2017-10-14',
                'aired_to' => '2017-10-14',
                'duration' => '120 min',
                'quality' => 'HD',
                'episode_current' => 1,
                'episode_total' => 1,
                'views_count' => 14510,
                'comments_count' => 17,
                'score' => 8.48,
                'score_count' => 1822,
                'rating_avg' => 8.3,
                'rating_count' => 214,
                'created_at' => $now,
                'updated_at' => $now,
                'genres' => ['action', 'drama', 'fantasy', 'romance'],
            ],
        ];

        foreach ($animes as $anime) {
            $genresForAnime = $anime['genres'];
            unset($anime['genres']);

            $animeTable->insert($anime);
            $animeId = (int) $this->db->insertID();

            foreach ($genresForAnime as $genreSlug) {
                if (! isset($genreIds[$genreSlug])) {
                    continue;
                }

                $animeGenreTable->insert([
                    'anime_id' => $animeId,
                    'genre_id' => $genreIds[$genreSlug],
                ]);
            }
        }
    }
}
